# Generated by Django 3.2.17 on 2023-02-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanagerapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
